name: session
description: WorkoutPro - A Notion-inspired workout builder
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_portal: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/session_builder_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/session_builder_icon.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/session_builder_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/session_builder_icon.png"
